name: Update Daily Quote
on:
  workflow_dispatch: # Allows manual run
  schedule:
    - cron: '0 2 * * *' # Runs at 02:00 UTC daily
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
